### PR TITLE
title: added blog on flask api authentication

### PR DESCRIPTION
**Pull request by LordGhostX**
#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Author Details for Blog Post Entry

id: Solomon Esenyi
bio: Python Developer and Technical Writer with a passion for open-source, cryptography, and serverless technologies.
github: LordGhostX
linkedin: solomon-esenyi
twitter: LordGhostX

### CODE REVIEW

**Comment by LordGhostX** [comment]
@pareek-narendra @puneetsingh24 is there anything I need to do for the article again?

**Comment by LordGhostX** [comment]
@pareek-narendra

**Comment by raghunath-r-a** [comment]
@LordGhostX We'll review this in some time and get back to you if changes are necessary

**Comment by raghunath-r-a** [comment]
Hi @LordGhostX 

First things first, apologies for the delayed review.

We have reviewed it and is missing the following from the initially discussed outline:

1. Registered user login
2. Non-registered user login
3. Implementing bearer token expiration time

Please try adding/creating content for the above sections. It will provide more comprehensive value for the readers.

Additionally, please add [this demo code](https://github.com/LordGhostX/flask-auth-demo) in this repo by raising a pull request: https://github.com/LoginRadius/engineering-blog-samples

Thank you,
@raghunath-r-a

**Comment by raghunath-r-a** [comment]
Closing this due to no response.

**Pull request closed without merging**
