### PR TITLE
Token vs Session Authentication Blog.

### PR DESCRIPTION
**Pull request by imrishabh18**
#### Checklist

- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] Checked for all grammatical errors in the blog.
- [x] Checked for any duplicate blog entry.
- [x] You PR is raised on `dev` branch and not on`master`.

##### Author Details for Blog Post Entry

Already added in the file.

### CODE REVIEW

**Comment by imrishabh18** [comment]
@vyasriday Can you please review my PR? 😃

**Review by puneetsingh24 — COMMENTED** [review]
Hello @imrishabh18 

Thanks for writing this blog and we appreciate your effort while writing this. However, as per our project contribution guidelines, we recommend writing a blog of around a minimum of 600 words, to make it more informative. 

We try to provide a detailed blog to our readers, You can elaborate on the differences and write and tell more about both authentications.

Thanks

**Comment by imrishabh18** [comment]
Hi @puneetsingh24 

I have added some more information about the advantages and stuff. This is all what I can think of 😅. Also, making it more than 600 words. Hopefully, this article is pretty clear to explain the difference between Session and Token Authentication.

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
Hello @imrishabh18 ,

We found out that most of the content on the blog is copy-pasted from another sites. As part of our code of conduct, we encourage you to create your own content in your own language. We are strongly against plagiarism and hence do not accept blog that is copy-pasted from the Internet.

Please update the content in your own language. If you want to submit the blog.

And please create a branch from dev and then create a pull request to merge on the dev branch

**Pull request closed without merging**
