### PR TITLE
typo in the code, pagination.js

### PR DESCRIPTION
**Pull request by midopooler**
#### Checklist

- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] You created a branch from `dev` branch
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] Checked for all grammatical errors in the blog.
- [x] Checked for any duplicate blog entry.
- [x] You PR is raised on `dev` branch and not on`master`.

##### Description of change

There was a typo in the script pagination.js

### CODE REVIEW

**Comment by vyasriday** [comment]
Pleae update the title of your PR to reflect your changes.

**Comment by vyasriday** [comment]
@midopooler Since both variables have same name and due to #342 I will have to close this PR.

**Comment by midopooler** [comment]
As I can see, issue #342 is posted after I posted this PR. Couldn't this PR be still valid?

**Comment by vyasriday** [comment]
I am sorry @midopooler But I also gave you the reason. The code is fine. It would have been a typo if they both has different names.

**Comment by midopooler** [comment]
Ok thank you @vyasriday

**Pull request closed without merging**
