### PR TITLE
Added Introduction to Android Studio Blog

### PR DESCRIPTION
**Pull request by prithvirajbytes**
#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Author Details for Blog Post Entry

id: Prithviraj Biswas
bio: Programming is not only my passion but is something that I developed over time with great effort. I am driven by my insatiable fascination for Computers I learn something new every day as there is so much yet to learn.
github: https://github.com/prithvirajbytes
stackoverflow:
linkedin: https://www.linkedin.com/in/prithviraj-biswas-a9a827169/
medium:
twitter:

### CODE REVIEW

**Comment by vyasriday** [comment]
@prithvirajbytes Please create your PR on dev branch and not on master.

**Comment by prithvirajbytes** [comment]
@vyasriday  Created my PR on dev branch #458. Please Review :)

**Comment by vyasriday** [comment]
That's still on the master. Raise your PR on dev and not master. Please read guidelines properly.

**Comment by prithvirajbytes** [comment]
@vyasriday Sorry for previous mistakes, created PR on dev branch #459 . Please review

**Pull request closed without merging**
