### PR TITLE
React Lazy Loading blog

### PR DESCRIPTION
**Pull request by akshay11298**
#### Checklist

- [ x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [ x] You created a branch from `dev` branch
- [ x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [ x] Checked for all grammatical errors in the blog.
- [ x] Checked for any duplicate blog entry.
- [ x] You PR is raised on `dev` branch and not on`master`.

##### Description of change
Added a new blog for Lazy loading in React

##### Author Details for Blog Post Entry

id: Akshay Avinash
bio: A tech enthusiast
github: github.com/akshay11298
linkedin: https://www.linkedin.com/in/akshay11298/

### CODE REVIEW

**Comment by KarenEfereyan** [comment]
Waow @akshay-s-770 this PR looks really good

**Review by puneetsingh24 — COMMENTED** [review]
Hello @akshay11298 

Thanks for writing this blog and we appreciate your effort while writing this. However, as per our project contribution guidelines, we recommend a cover image of min size 900px X 600px

Can you reupload the hight resolution image

**Comment by akshay11298** [comment]
Hi @puneetsingh24 
I have reuploaded the cover image with the expected resolution of 900 x 600 px.

**Review by vyasriday — APPROVED** [review]
Nice article @akshay11298

**Pull request merged**
