### PR TITLE
Added stale bot GitHub action

### PR DESCRIPTION
**Pull request by iamrajiv**
#### Checklist

- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] Checked for all grammatical errors in the blog.
- [x] Checked for any duplicate blog entry.

##### Description of change

Fixes: #285

### CODE REVIEW

**Comment by iamrajiv** [comment]
@vyasriday Please review.

**Comment by iamrajiv** [comment]
@puneetsingh24 Please review.

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
Hello @iamrajiv, Thanks for your contribution. It looks like that the code for stale action you contributed is from this action - https://github.com/probot/stale-action which has been deprecated.

Please contribute the latest code or please share the source of information.

**Comment by iamrajiv** [comment]
@puneetsingh24 I have updated the stale bot action.

**Pull request closed without merging**
