### PR TITLE
ADD Blog on VDN

### PR DESCRIPTION
**Pull request by agarwalBinay18**
updated index.md and MIM.jpg in the directory under blog directory

#### Checklist

- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] You created a branch from `dev` branch
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] Checked for all grammatical errors in the blog.
- [x] Checked for any duplicate blog entry.
- [x] You PR is raised on `dev` branch and not on`master`.

##### Author Details for Blog Post Entry

id: Binay Agarwal
bio: A CyberSecurity Geek
github:agarwalBinay18

### CODE REVIEW

**Comment by agarwalBinay18** [comment]
@pareek-narendra Please review my PR 👍 )

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
Hello @agarwalBinay18

Thanks for writing this blog and we appreciate your effort while writing this. However, as per our project contribution guidelines, You need to create a PR against the dev branch.

Cover image size should be in ratio 3:2 and minimum size should be 900px X 600px

Blog content should consist of a minimum of 600-900 words

Please do the necessary changes. Thanks

**Comment by agarwalBinay18** [comment]
please check it @puneetsingh24 . I have rectified the issues

**Review by puneetsingh24 — COMMENTED** [review]
@agarwalBinay18 Thanks for the changes, still I can't see the cover image is not of size 900px X 600px or more than that.

And the conclusion part of the blog is directly the same from the blog - https://www.forbes.com/sites/jasonbloomberg/2014/10/16/cybersecurity-turning-the-tide-on-hackers-with-dispersive-technologies/

Can you please write that whole paragraph in your own language?

**Comment by agarwalBinay18** [comment]
@puneetsingh24  I have updated para and resize the image.Kindly check it

**Review by puneetsingh24 — APPROVED** [review]

**Review by vyasriday — APPROVED** [review]

**Pull request merged**
