### PR TITLE
Adding new material about machine learning for beginner

### PR DESCRIPTION
**Pull request by nandiya**
Description: mainly focus on data preprocessing
which is the initial step before stepping further
with computer science

#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

### CODE REVIEW

**Comment by nandiya** [comment]
@puneetsingh24 I have added new material based on my own style and experience in my company, can you please review it^^

**Comment by nandiya** [comment]
@vyasriday please check if it's okay or not.. i already resolved the conflict since it's been too long and has new authors

**Comment by abhir9** [comment]
@nandiya  please get update/rebase your PR to get merge

**Comment by raghunath-r-a** [comment]
@nandiya Somehow, this PR has been missed. Can you please update your Author details as per [the guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md)?

**Comment by raghunath-r-a** [comment]
The PR is being closed as there has been no response from the author.

**Pull request closed without merging**
