### PR TITLE
added the blog on Blockchain

### PR DESCRIPTION
**Pull request by shraddhavp**
#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Description of change

Added the blog on Blockchain technology

##### Author Details for Blog Post Entry

id: Shraddha Prasad
bio : Developer in the making,blogger by passion,Open source enthusiast
github: https://github.com/shraddhavp
stackoverflow: https://stackoverflow.com/users/14385751/shraddha-v-prasad
linkedin:https://www.linkedin.com/in/shraddha-prasad-6a60b0188/
medium: https://medium.com/@anitha.shraddha
twitter: https://twitter.com/shraddhavprasa1

this PR is related to #233

### CODE REVIEW

**Comment by shraddhavp** [comment]
@puneetsingh24 sir  and @vyasriday sir added the blog on blockchain please look into it and let me know if any changes

**Review by puneetsingh24 — COMMENTED** [review]
Hello @shraddhavp 

Thanks for writing this blog and we appreciate your effort while writing this. However, as per our project contribution guidelines, we recommend a cover image of ratio 3:2 with a minimum image size of 900px X 600px. 

Can you please update the cover image as per the guidelines

Thanks

**Comment by shraddhavp** [comment]
@puneetsingh24  sir  added the new image as per the changes told please check

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
@shraddhavp First we need an image of ratio 3:2, your update doesn't follow this. Second, we don't just resize the image to a bigger size, it pixelated the image.

You can search new image from below two resources

https://unsplash.com/
https://pixabay.com/

Thanks

**Comment by shraddhavp** [comment]
ok thank sir @shraddhavp  i will look into it and will open a new PR on the same

**Pull request closed without merging**
