### PR TITLE
Blog on how to make a telegram bot

### PR DESCRIPTION
**Pull request by rjn01**
#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Description of change
Added a blog describing bot and how to make our own Telegram bot.

##### Author Details for Blog Post Entry
Name: Rajan Puri
Github: rjn01

#233

### CODE REVIEW

**Comment by rjn01** [comment]
@puneetsingh24 can you tell me if the blog is okay or if there are some changes that to be made?

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
Hello @rjn01 

Thanks for writing this blog and we appreciate your effort while writing this. However, as per our project contribution guidelines, we recommend committing the source code used in the blog post to the repo - https://github.com/LoginRadius/engineering-blog-samples

Can you please create a pull request of source code in the above repo and then mention the link in the blog.

Thanks

**Review by puneetsingh24 — COMMENTED** [review]
@rjn01 I have done a few changes myself, please take a pull before doing any new changes

**Comment by rjn01** [comment]
@puneetsingh24 You have done the grammatical changes, the only thing I have to do is to change the link of the source code. Right?

**Review by puneetsingh24 — COMMENTED** [review]
@rjn01 You have to push code in above mention repo and change the link only, yes

**Comment by rjn01** [comment]
@puneetsingh24 I have added the link. Can you review it and tell if any further changes has to be done. Also, review the sample code pull request.

**Review by puneetsingh24 — APPROVED** [review]

**Review by vyasriday — APPROVED** [review]

**Pull request merged**
