### PR TITLE
Added blog on Class activation mapping

### PR DESCRIPTION
**Pull request by Ankit810**
#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Author Details for Blog Post Entry
id: Ankit Choraria
github: https://www.github.com/Ankit810
LinkedIn: https://www.linkedin.com/in/ankit-choraria-3b45a1181/

### CODE REVIEW

**Comment by Ankit810** [comment]
@puneetsingh24 sir and @vyasriday sir, please can anyone of you review it?

**Review by vyasriday — APPROVED** [review]

**Review by puneetsingh24 — APPROVED** [review]

**Comment by Ankit810** [comment]
Hey @vyasriday sir!
Thank you for merging my blog!
However, there is one issue. When I preview my `index.md` file on GitHub, the equations don't seem to be converted properly. The '$' sign is still visible in the preview. Is this a bug? Or any syntax error from my side? Please let me know...

**Comment by vyasriday** [comment]
@Ankit810 Thanks for reaching out. So you wanted it to be like `f(x,y)` but it rather look like this `$f(x,y)$ `. is it?

**Comment by Ankit810** [comment]
Yes @vyasriday sir!
According to the syntax, I had typed single `$` for inline equations and `$$` for equations on a new line. Even on the blog site (https://www.loginradius.com/engineering/blog/class-activation-mapping/), the issue persists. Any way to rectify this?

**Comment by vyasriday** [comment]
@Ankit810 So basically those $ signs are the only thing that are not required in the equations, right? For example `\Large S_{c}= \sum_{k}w^{c}_{k}F_{k}` is right equation rather than $$\Large S_{c}= \sum_{k}w^{c}_{k}F_{k}$$.

**Comment by Ankit810** [comment]
Hey @vyasriday sir!
There is a syntax issue. I'll create a separate PR for the same?

**Comment by vyasriday** [comment]
@Ankit810 You don't have to create a separate PR. I have fixed it. Will let you know once I make it live.

**Comment by Ankit810** [comment]
> @Ankit810 You don't have to create a separate PR. I have fixed it. Will let you know once I make it live.

Alright!
Sorry for the syntax issue from my end...

**Comment by vyasriday** [comment]
@Ankit810 So it's basically latex code? For now I have made it like `\Large P_{c}=\frac{e^{S_{c}}}{\sum_{c}e^{S_{c}}}`. is this valid?

**Comment by Ankit810** [comment]
> @Ankit810 So it's basically latex code? For now I have made it like `\Large P_{c}=\frac{e^{S_{c}}}{\sum_{c}e^{S_{c}}}`. is this valid?

Yes sir, the equations are in latex.
You can refer this for more clarity: https://www.youtube.com/watch?v=dpVnmxpVdvg

**Comment by vyasriday** [comment]
So this one is 

> @Ankit810 So it's basically latex code? For now I have made it like `\Large P_{c}=\frac{e^{S_{c}}}{\sum_{c}e^{S_{c}}}`. is this valid?

so is this valid now or not?

**Comment by Ankit810** [comment]
Sir any latex equation will have to follow the same syntax:-
Any label

All the equations mentioned in my blog are correct and valid. It's just that we have to follow these steps:
1. Go to https://www.codecogs.com/latex/eqneditor.php
2. Copy paste the equations mentioned in my blog one by one
3. Generate a .png format answer and copy it's image address link
4. Follow the  syntax for github .md files

**Comment by vyasriday** [comment]
@Ankit810 Please take a pull and create a separate PR with the fixes as early as possible.

**Comment by Ankit810** [comment]
> @Ankit810 Please take a pull and create a separate PR with the fixes as early as possible. You need to rebase with dev first.

Sorry for the inconvenience caused. I'll update the fork and generate a PR ASAP

**Comment by Ankit810** [comment]
PR raised #408 

Please have a look @vyasriday

**Comment by vyasriday** [comment]
@Ankit810 It's merged and please don't call sir 😄

**Comment by vyasriday** [comment]
@Ankit810 Please check your blog [Class Activation Mapping in Deep Learning](https://www.loginradius.com/engineering/blog/class-activation-mapping/).

**Comment by Ankit810** [comment]
Hey @vyasriday thank you so much!

**Pull request merged**
