### PR TITLE
Updated Cover image of issue #231 to 1200 X 800 pixels

### PR DESCRIPTION
**Pull request by Ashumaurya**
#### Checklist

- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] You created a branch from `dev` branch
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] Checked for all grammatical errors in the blog.
- [x] Checked for any duplicate blog entry.
- [x] You PR is raised on `dev` branch and not on`master`.

### CODE REVIEW

**Review by vyasriday — COMMENTED** [review]
@Ashumaurya Thanks for contributing. But we prefer relative URLs compared to absolute URLs due to multiple deployment environments.

**Comment by Ashumaurya** [comment]
> @Ashumaurya Thanks for contributing. But we prefer relative URLs compared to absolute URLs due to multiple deployment environments.

@vyasriday Hello I think there been a misunderstanding I solved issue #231. I m new to open source so sorry for any inconvenience.

**Comment by vyasriday** [comment]
@Ashumaurya Okay. Please provide proper title to PR so that I can see properly what it's about.

**Comment by Ashumaurya** [comment]
@vyasriday Thankyou for being patient with me. I have updated the PR title to a relevant one. I hope this works.

**Comment by vyasriday** [comment]
Can you please rebase your branch with `dev` branch and then push it.

**Comment by Ashumaurya** [comment]
Sure I will do that.

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
Image size is not of 1200px width and 800px height

**Comment by Ashumaurya** [comment]
@puneetsingh24 I changed the image size as requested now.

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
@Ashumaurya Please remove all other changes(relative URLs) except the image change from the pull request

**Comment by Ashumaurya** [comment]
@puneetsingh24 Done with the requested change. Please have a look. :)

**Pull request closed without merging**
