### PR TITLE
bluetooth-controlled-arduino-car-miniature

### PR DESCRIPTION
**Pull request by Madmaxcoder2612**
#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

### CODE REVIEW

**Comment by Madmaxcoder2612** [comment]
Hello sir , Any update regarding this blog , any changes required ?

**Comment by Madmaxcoder2612** [comment]
Hello sir, @puneetsingh24 @vyasriday , Can you please review my blog, If any changes or suggestion ,so that i can improve .

**Comment by vyasriday** [comment]
@Madmaxcoder2612 Please change the name of the folder.  `Bluetooth Controlled Arduino Car Miniature/ ` should be `bluetooth-controlled-arduino-car-miniature/`.

**Comment by Madmaxcoder2612** [comment]
Hello sir, I have Updated the content and other things as you said , Thank you for your Response !

**Comment by Madmaxcoder2612** [comment]
Hello @vyasriday sir , i have updated every changes that were required , please review the Blog once !

**Review by puneetsingh24 — APPROVED** [review]

**Comment by Madmaxcoder2612** [comment]
Thank you @puneetsingh24 sir , for approving and helping to improve !

**Pull request merged**
