### PR TITLE
Blog :  JWT, JWS, JWE, JWK, and JWA

### PR DESCRIPTION
**Pull request by Yashesvinee**
#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Description of change
Added content on What are JWT, JWS, JWE, JWK, and JWA
Issue #758

### CODE REVIEW

**Comment by raghunath-r-a** [comment]
Hi @Yashesvinee 

We did the first phase of the review and edited the content for improvements. To take it forward to the next phase, please do the following changes:

- Add your author bio in `author.yaml` file, under `- id: "Yashesvinee V"`
- For the images you have added in the blog content, please add relevant sources in `<figcaption>` tag
- Add a `conclusion` section before the references and summarize your blog post

Best,
@raghunath-r-a

**Comment by Yashesvinee** [comment]
@raghunath-r-a I have made the required changes 
please let me know if any more changes are required

**Comment by raghunath-r-a** [comment]
@Yashesvinee Thanks for the changes. We're moving this to the next phase of review, and you'll hear from us if further changes are necessary by mid-next-week.

**Review by nathannguyenn — APPROVED** [review]
Content has been reviewed, everything looks good to me

**Pull request merged**
