### PR TITLE
Implementing User Authentication and Registration in Flutter using LoginRadius API. 

### PR DESCRIPTION
**Pull request by iloveteajay**
#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

### CODE REVIEW

**Review by raghunath-r-a — CHANGES_REQUESTED** [review]
Hi @iloveteajay We're moving your submission to Phase-11. 

Please add sample code in the following repo by creating a seperate pull request: https://github.com/LoginRadius/engineering-blog-samples

**Comment by iloveteajay** [comment]
Hello @raghunath-r-a. I have added the code to the repo.

**Review by akaashsaxena2897 — CHANGES_REQUESTED** [review]
Hi, in index.md from line #240 onwards. Kindly provide instructions as to in which file and where does this code needs to be inserted in the project. It'd be helpful if you can provide a folder structure as well, since the sample project repo and the guide followed here seems to follow a different folder structure

**Review by akaashsaxena2897 — APPROVED** [review]
Seems fine on my end

**Review by raghunath-r-a — APPROVED** [review]

**Pull request merged**
