### PR TITLE
Added new bog: Optimal clusters for KMeans Algorithm 

### PR DESCRIPTION
**Pull request by NEERAJAP2001**
#### Checklist

- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] You created a branch from `dev` branch
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] Checked for all grammatical errors in the blog.
- [x] Checked for any duplicate blog entry.
- [x] You PR is raised on `dev` branch and not on`master`.

##### Author Details for Blog Post Entry

id: Neeraj Ap
bio: A computer science and engineering undergraduate.
github: https://github.com/NEERAJAP2001
linkedin: :https://www.linkedin.com/in/neeraj-adityananth/

### CODE REVIEW

**Review by puneetsingh24 — COMMENTED** [review]
Hello @NEERAJAP2001 

Thanks for writing this blog and we appreciate your effort while writing this. However, as per our project contribution guidelines, we recommend writing a blog of around a minimum of 600 words, to make it more informative.

We try to provide a detailed blog to our readers, Can you please add more information in the post

Thanks

**Review by puneetsingh24 — COMMENTED** [review]
Hello @NEERAJAP2001 

Also please add cover image of ratio 3:2, we recommend image size of 1200px:800px or minimum 900px:600px

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
Hello @NEERAJAP2001 

We found out that most of the text content on the blog is copy-pasted from other sites. As part of our code of conduct, we encourage you to create your own content in your own language. We are strongly against plagiarism.

https://www.guru99.com/unsupervised-machine-learning.html

https://www.analyticsvidhya.com/blog/2019/08/comprehensive-guide-k-means-clustering/

https://towardsdatascience.com/understanding-k-means-clustering-in-machine-learning-6a6e67336aa1

https://github.com/MihailaDumitru/K-Means_Clustering

Please update the content of the text in your own language if you would like to submit the blog.

Thanks

**Comment by NEERAJAP2001** [comment]
I copied only a few of the definitions(cause they are easily understandable and intuitive). I've changed them now with my text!! 
peace!
@puneetsingh24

**Comment by NEERAJAP2001** [comment]
@puneetsingh24  pelaced the content !! can you please check now?

**Comment by NEERAJAP2001** [comment]
@puneetsingh24  replaced the content !! Could you please check?

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
Hello @NEERAJAP2001

Also please add cover image of ratio 3:2, we recommend image size of 1200px:800px or minimum 900px:600px

**Image size is not in ratio 3:2**,

**Review by puneetsingh24 — APPROVED** [review]

**Review by vyasriday — APPROVED** [review]

**Pull request merged**
