### PR TITLE
Created Blog speed-up-python-code 

### PR DESCRIPTION
**Pull request by tahmid02016**
#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Description of change
Added blog on how to speed up (decrease runtime) python programme.

##### Author Details for Blog Post Entry

id: Md. Tahmid Hossain
bio: I am a programmer, developer and digital-marketer.
github: https://github.com/tahmid02016

### CODE REVIEW

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
Hello @tahmid02016 

Thanks for writing this blog and we appreciate your effort while writing this. However, as per our project contribution guidelines, we need the blog of 600-900 words minimum.

Can you please add more information.

**Comment by tahmid02016** [comment]
> Hello @tahmid02016
> 
> Thanks for writing this blog and we appreciate your effort while writing this. However, as per our project contribution guidelines, we need the blog of 600-900 words minimum.
> 
> Can you please add more information.

I have added more content. Please check it now.

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
Hello @tahmid02016 thanks for updating the content, I also have done some changes to fix typos and grammar.

Can you please change the cover image also, you can use free sites like - https://www.canva.com/ to create some good cover image. 

Right now the cover image is not looking up to the mark

**Comment by tahmid02016** [comment]
Thank you very much @puneetsingh24 for fixing the typos.
I have uploaded a new cover image.  Please have a look at that. Thank you.

**Review by vyasriday — APPROVED** [review]

**Review by puneetsingh24 — APPROVED** [review]

**Pull request merged**
