### PR TITLE
the-competitive-programming-guide Blog ISSUE #233

### PR DESCRIPTION
**Pull request by arshita129**
##

#### Checklist

- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] You created a branch from `dev` branch
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] Checked for all grammatical errors in the blog.
- [x] Checked for any duplicate blog entry.
- [x] You PR is raised on `dev` branch and not on`master`.

##### Author Details for Blog Post Entry

#233

### CODE REVIEW

**Review by puneetsingh24 — COMMENTED** [review]
Hello @arshita129 

Thanks for writing this blog and we appreciate your effort while writing this. However, as per our project contribution guidelines, we recommend writing a blog of around a minimum of 600 words, to make it more informative.

We try to provide a detailed blog to our readers, You can tell about some pros/cons of competitive programming, or add more resources related to it.

And please try to create a feature branch from dev and then create a pull request on the dev branch

Thanks

**Review by puneetsingh24 — COMMENTED** [review]
@arshita129 Also please upload the cover image of ratio 3:2 we recommend the size 1200x800 and minimum 900x600

**Comment by arshita129** [comment]
Hello @puneetsingh24 Sorry for these issues. I have again made a fresh pull request keeping all these points in mind. Please review it. #351

**Review by puneetsingh24 — COMMENTED** [review]
@arshita129 Can you please confirm which one is the final pull request #351 #352

**Comment by puneetsingh24** [comment]
Contributor created a new pull request

**Comment by arshita129** [comment]
> @arshita129 Can you please confirm which one is the final pull request #351 #352

#352 is the final one.

**Pull request closed without merging**
