### PR TITLE
Blog Added : Build Smart Contract using Ethereum Blockchain to book Hostel

### PR DESCRIPTION
**Pull request by belelaritra**
title: Build Smart Contract using Ethereum Blockchain to book PG

description: Build your first smart contract using solidity, where you can upload your PG for rent, people can sign rental agreement and pay rent.

#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Description of change
1.  Script Modified : `content/author.yaml` 
2. Script Added : `content/guest-post/decentralised-pg-booking-system-using-ethereum-smart-contract/index.md`
3. CoverImage Added : `content/guest-post/decentralised-pg-booking-system-using-ethereum-smart-contract/coverimage.png`

### CODE REVIEW

**Comment by belelaritra** [comment]
> Hi @belelaritra
>
> We need the following changes from your end:
> 
> 1. In lines 228, 247, 262, 275, and 292, the description is confusing. Please try editing to clarify it.
> 2. Please do not use remote images. Place images in the same folder as `index.md` and refer to them locally in the `index.md` file
> 3. Please aptly change `PG` to `hostel` throughout the content, as our global audience can easily understand what a hostel is rather than a PG.
> 
> Once you do these changes, let us know. We'll do a final phase of review to take it forward.
> 
> Best, @raghunath-r-a

@raghunath-r-a ,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1. I have modified `index.md` according to the requested format.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2. Sample images added under the same folder. 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3. Word `Pg` changed into `Hostel` throughout the content. (Same for the [code](https://github.com/LoginRadius/engineering-blog-samples/pull/128) also)

**Comment by raghunath-r-a** [comment]
@belelaritra Thanks for the changes. 

I have improved the content a bit more and moved it to the final phase of the review. 

We'll update you once we're done with the review. 

Best,
@raghunath-r-a

**Comment by belelaritra** [comment]
@raghunath-r-a any update?

**Comment by raghunath-r-a** [comment]
Hi @belelaritra This is getting a bit delayed as smart contacts are something our technical reviewers aren't familiar with. You'll surely get an update from us by the end of next week.

**Comment by belelaritra** [comment]
> Hi @belelaritra This is getting a bit delayed as smart contacts are something our technical reviewers aren't familiar with. You'll surely get an update from us by the end of next week.

Oh ok.

Just one more question sir. 
Am I eligible for LoginRadius Swags?

As, [here](https://www.loginradius.com/blog/async/hacktoberfest-2021/) it was written that, <br>`"We want to make it more fun by sending cool t-shirts to all the accepted/eligible contributors. Just make sure to fill this form after you raise a pull request.`

**Comment by raghunath-r-a** [comment]
> > Hi @belelaritra This is getting a bit delayed as smart contacts are something our technical reviewers aren't familiar with. You'll surely get an update from us by the end of next week.
> 
> Oh ok.
> 
> Just one more question sir. Am I eligible for LoginRadius Swags?
> 
> As, [here](https://www.loginradius.com/blog/async/hacktoberfest-2021/) it was written that, `"We want to make it more fun by sending cool t-shirts to all the accepted/eligible contributors. Just make sure to fill this form after you raise a pull request.`

Yes, you're eligible. Our team will contact you regarding the same in the next few weeks on your email-id submitted to us.

**Review by Akash-Patil — CHANGES_REQUESTED** [review]
Hi @belelaritra, 

Firstly, we apologise for the delay. 

I have reviewed the blog and requested a few changes. Please have a look and let me know in case of any queries. 
Also, resolve the conflicts on this branch so that we can merge it once the changes have been made.

Regards,
@Akash-Patil

**Comment by belelaritra** [comment]
> I have reviewed the blog and requested a few changes. Please have a look and let me know in case of any queries. Also, resolve the conflicts on this branch so that we can merge it once the changes have been made.

Hi @Akash-Patil , 

Thank you for pointing out my mistakes.
I have modified the [`index.md`](https://github.com/LoginRadius/engineering-portal/pull/849/commits/56155bdc1a4e608f287a4e47e7e27bbd923db20b) file as per the request. Also, I have resolved the conflict inside [`content/author.yaml`](https://github.com/LoginRadius/engineering-portal/pull/849/commits/87f20aa027e6fb814892f1930d1b0bfecb026d2f) file. PTAL.

Regards,
@belelaritra

**Review by Akash-Patil — APPROVED** [review]
Hi @belelaritra, 

Changes look good from my end. We will publish the blog soon.

Regards,
@Akash-Patil

**Comment by raghunath-r-a** [comment]
Hi @belelaritra We're merging your PR. Please update your GitHub profile picture to something more relevant, like your own picture or a default gravatar on GitHub. Your GitHub profile will be shown in your author bio in the [Async Blog](https://www.loginradius.com/blog/async/).

**Comment by raghunath-r-a** [comment]
Hi @belelaritra Congrats! You blog has been published: https://www.loginradius.com/blog/async/guest-post/ethereum-smart-contract-tutorial/

Please do share it with your network and on social media

**Comment by belelaritra** [comment]
Thank you so much @raghunath-r-a.

**Pull request merged**
