### PR TITLE
Issue fixed #234; Added information and summary of Argon2 hash functio…

### LINKED ISSUE #234: Put detail about argon2 hashing in the blog post about encryption and hashing
https://www.loginradius.com/engineering/blog/encryption-and-hashing/

The above blog contains introductory detail about many hashing and encryption algorithms, Need to add the details about argon2 hashing also

### PR DESCRIPTION
**Pull request by JanetLaysEggs**
…n. -J

#### Checklist

- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] Checked for all grammatical errors in the blog.
- [x] Checked for any duplicate blog entry.

##### Description of change

#234; Added information and summary of Argon2 hash function. -J

##### Author Details for Blog Post Entry
id: JanetLaysEggs
bio: 'Just a simple country girl'
github: https://github.com/JanetLaysEggs
stackoverflow:
linkedin:
medium:
twitter:

### CODE REVIEW

**Comment by JanetLaysEggs** [comment]
Want this to count towards Hacktoberfest - will repost then. Sorry for the delay! -J

**Comment by vyasriday** [comment]
No Problems @JanetLaysEggs . We would love to help you become eligible for hacktoberfest. Meanwhile, feel free to checkout our [Hacktoberfest Page](https://www.loginradius.com/engineering/page/hacktoberfest2020) to know more about LoginRadius offerings for the hacktoberfest.

**Comment by JanetLaysEggs** [comment]
Thank you @vyasriday! If you would like me to add to/change my work in anyway I'd be more than happy to fix it.

**Comment by JanetLaysEggs** [comment]
Hey @vyasriday someones has posted a PR and it has been approved by @puneetsingh24! What happens now?

**Pull request closed without merging**
