### PR TITLE
Technical Blog on "Introductions to Github actions for Android"

### PR DESCRIPTION
**Pull request by akshitagupta15june**
#### Checklist

- [X] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [X] You created a branch from `dev` branch
- [X] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [X] Checked for all grammatical errors in the blog.
- [X] Checked for any duplicate blog entry.
- [X] You PR is raised on `dev` branch and not on`master`.

### Author Information

id: Akshita Gupta
bio: Meticulous and motivated undergraduate student , indulged in competitive programming,Android, field of interest is Computer Vision. My BTech is focused in Computer Science and I am an open-source enthisiast. 
github:akshitagupta15june
linkedin:https://www.linkedin.com/in/akshita-gupta-a4a895187/
medium:https://medium.com/@akshitagupta15june
twitter:https://twitter.com/Akshita_archer/

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Please have a look at my technical blog!

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
Hello @akshitagupta15june 

Thanks for writing this blog and we appreciate your effort while writing this. However, as per our project contribution guidelines, You need to create a feature branch from dev and then create a PR against the dev branch.

Please do the necessary changes. Thanks

**Comment by akshitagupta15june** [comment]
Ok i will do it by dev branch can you please tell the process.

**Review by puneetsingh24 — COMMENTED** [review]
You need to add your blog in the dev branch of your repo and then create a pull request from dev to LoginRadius/engineering-portal/dev as shown in below image

dev

**Comment by akshitagupta15june** [comment]
sir please check  have raised a pull request

**Review by puneetsingh24 — COMMENTED** [review]
@akshitagupta15june You need to create the pull reqeust from your dev branch, you need to add your blog in your dev branch, please check the above screenshot

**Comment by puneetsingh24** [comment]
Contributor created a new pull request

**Pull request closed without merging**
