### PR TITLE
Add blog on how to create an accordion with only HTML and CSS

### PR DESCRIPTION
**Pull request by anohene1**
```
   id: Isaac Anohene
   github: anohene1
   linkedin: isaac-anohene-688276159
   twitter: anohene1
   ```

### CODE REVIEW

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
@anohene1 We appreciate your efforts, but as per our guideline, you should create a feature branch from the dev branch and then create a pull request on the dev branch.

Please do the changes

**Comment by anohene1** [comment]
I'm sorry, but I think that's what I did. However, if that's not what I did, can you kindly give me more info as to what I'm supposed to do? Thanks.

**Comment by vyasriday** [comment]
@anohene1 As per our [Contribution Flow](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md#contribution-flow), once you fork you need to switch to `dev` branch and from there push to your `dev` and raise pull request. I believe right now you just forked and started working on the forked copy which was on the master branch. So here's what you need to do now:
1. Close this PR.
2. Delete your fork (Go to [Your Repo](https://github.com/anohene1/engineering-portal) and in settings see delete option)
3. Create  a fresh fork the same way you forked previously
4. Once forked clone it and switch to dev branch `git checkout dev`
5. The do your changes and raise a PR on `dev` branch.

Let me know if this works for you.

**Comment by anohene1** [comment]
Sure. I'll go ahead and do that. Thanks

**Comment by anohene1** [comment]
I've done that. Thanks

**Pull request closed without merging**
