### PR TITLE
title: blog on GitHub CLI 1.0

### PR DESCRIPTION
**Pull request by SaravananVijayamuthu**
title: done a blog on GitHub CLI 1.0

### CODE REVIEW

**Comment by vyasriday** [comment]
LGTM, I will close this one #243 and put this PR  under review.

**Comment by SaravananVijayamuthu** [comment]
> LGTM, I will close this one #243 and put this PR under review.

Ok, vyasriday Thanks!!

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
Hello @SaravananVijayamuthu 

Thanks for writing this blog and we appreciate your effort while writing this. However, as per our contribution guidelines, We are looking for posts that are not published elsewhere.

But you have already published this blog on [medium](https://medium.com/coderbyte/github-cli-tool-a728b28493cd), We recommend you to add different information regarding the same topic or please choose another topic.

Thanks

**Comment by SaravananVijayamuthu** [comment]
> Hello @SaravananVijayamuthu
> 
> Thanks for writing this blog and we appreciate your effort while writing this. However, as per our [contribution guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md), We are looking for posts that are not published elsewhere.
> 
> But you have already published this blog on [medium](https://medium.com/coderbyte/github-cli-tool-a728b28493cd), We recommend you to add different information regarding the same topic or please choose another topic.
> 
> Thanks

I can understand can I remove that blog in medium? Is that OK. Because I have covered all my views I have no idea to add more. Else, I have to do another blog.

**Comment by vyasriday** [comment]
@SaravananVijayamuthu What you can do is add a canonical URL on medium and remove the post from there.

**Review by puneetsingh24 — COMMENTED** [review]
@SaravananVijayamuthu Yes you can remove the post from the medium, publish it on LoginRadius then later you can import the same post to medium with canonical link

**Comment by SaravananVijayamuthu** [comment]
> @SaravananVijayamuthu What you can do is add a canonical URL on medium and remove the post from there.

Ok, I have deleted it from my medium please do check it. Once my blog is published here I'll import it again to my medium through canonical URL.

**Review by SaravananVijayamuthu — COMMENTED** [review]
I have done the changes please do verify it.

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
Hello @SaravananVijayamuthu 

We found out that a few of the content on the blog is copy-pasted from other sites. As part of our code of conduct, we encourage you to create your own content in your own language.

https://morioh.com/p/39a1bb9ab353

Please update the content of the text in your own language if you would like to submit the blog.
And please upload the different cover image too, that is same from this blog
Thanks

**Comment by SaravananVijayamuthu** [comment]
> Hello @SaravananVijayamuthu
> 
> We found out that a few of the content on the blog is copy-pasted from other sites. As part of our code of conduct, we encourage you to create your own content in your own language.
> 
> https://morioh.com/p/39a1bb9ab353
> 
> Please update the content of the text in your own language if you would like to submit the blog.
> And please upload the different cover image too, that is same from this blog
> Thanks

OMG! That's not plagiarism read https://morioh.com/p/39a1bb9ab353 this full. They have promoted my article which I had published earlier on medium 
Screenshot_20201002-145227. You can see here in this screenshot. That's my own article you can find my github profile pic too. They have just promoted. Even you can see medium link they have mentioned below. But now you can't access the link since I have deleted the post from medium.

**Review by SaravananVijayamuthu — COMMENTED** [review]
Please do review!

**Review by puneetsingh24 — APPROVED** [review]

**Review by vyasriday — APPROVED** [review]

**Pull request merged**
