### PR TITLE
Blog Post on "IoT & AI: The Perfect Match!"

### PR DESCRIPTION
**Pull request by Devanshh**
#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Description of change
Added a Blog Post

##### Author Details for Blog Post Entry

Author Details for Blog Post Entry

Id: Devansh Agarwal

Bio: Devansh is a Data Analyst with a high degree of inclination towards Business Intelligence and Digital Analytics. He is working as a Technical Content Writer from past couple of years. He has worked in various leadership roles and drastically increased the organization’s footprint, both digitally and authoritatively. As a public speaker, he led sessions on Writing and Technology. He thinks that Data has the power to shape people’s outlook towards things.

Github: https://github.com/Devanshh
Linkedin: https://www.linkedin.com/in/devansh-agarwal-a70474153/
Medium: https://medium.com/@devanshagarwal121
DEV: https://dev.to/devanshh

### CODE REVIEW

**Comment by vyasriday** [comment]
@Devanshh You have create 3 PRs and they all have same changes in them? You need any help with that? Because I can see thet all have both the new one as well the previous blog.

**Comment by Devanshh** [comment]
> @Devanshh You have create 3 PRs and they all have same changes in them? You need any help with that buddy? Because I can see thet all have both the new one as well the previous blog. 

Yes! Actually, I'm really confused. I tried raising a new PR, but it was giving some error. Can you please tell me, what should I do now?

**Comment by Devanshh** [comment]
Hi @vyasriday I have closed the previous PRs and deleted the files of previous post.

Can you please check it now?

**Comment by vyasriday** [comment]
@Devanshh I have deleted files for the previous blog but still can't remove the image for that. Also, you need to rename the folder so that it does not contain any spaces. So either you can do those changes or give me access to your fork and I will take care of that as for now I can not push any changes to your reop.

**Comment by Devanshh** [comment]
Fair enough @vyasriday , how can I give you the access?

**Comment by Devanshh** [comment]
Is there any update? @vyasriday

**Comment by vyasriday** [comment]
Hi @Devanshh We have got a couple of blogs to review. I will put your blog under review soon and will let you for any changes.

**Review by vyasriday — APPROVED** [review]

**Review by puneetsingh24 — APPROVED** [review]

**Pull request closed without merging**
