### PR TITLE
Blog Post on Role Based authentication with LoginRadius and ReactJS

### PR DESCRIPTION
**Pull request by Victory-ET**
#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

### CODE REVIEW

**Comment by Victory-ET** [comment]
Hi @raghunath-r-a 

I have created the new pull request and checked "allow edit by maintainers".

Regards,
@Victory-ET

**Comment by raghunath-r-a** [comment]
Thank you, @Victory-ET 

We'll review this in the next week and schedule it for publishing in the first week of September.

**Comment by Victory-ET** [comment]
Hello @raghunath-r-a 

Please when will the review process start

**Comment by raghunath-r-a** [comment]
Closing this PR as it is raised against **master** instead of **dev**.

#737 has been raised to correct this.

**Pull request closed without merging**
