### PR TITLE
Added Blog on HTML Email Concept

### PR DESCRIPTION
**Pull request by Nivedita967**
#### Checklist

- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] You created a branch from `dev` branch
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] Checked for all grammatical errors in the blog.
- [x] Checked for any duplicate blog entry.
- [x] You PR is raised on `dev` branch and not on`master`.

##### Description of change
Added a new Blog on HTML Email Concept

##### Author Details for Blog Post Entry
id: Nivedita Singh
bio: B. Tech Student, Nivedita Singh is a passionate Web Developer and  is an open source enthusiast.
GitHub: https://github.com/Nivedita967
LinkedIn: https://www.linkedin.com/in/nivedita-singh-195b6818a/
twitter: https://twitter.com/Nivedit95025806

### CODE REVIEW

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
Hello @Nivedita967,

We found out that most of the content on the blog is copy-pasted from other sites. As part of our code of conduct, we encourage you to create your own content in your own language. We are strongly against plagiarism and hence do not accept this blog.

https://blog.hubspot.com/marketing/html-email

https://www.tothenew.com/blog/html-email-fundamentals/

Please update the content of the text in your own language if you would like to submit the blog.

Thanks

**Comment by Nivedita967** [comment]
Please review once.

**Review by puneetsingh24 — COMMENTED** [review]
Hello @Nivedita967, It still has many points similar to the blog post - https://www.tothenew.com/blog/html-email-fundamentals/

Please write those content also in your language

**Comment by Nivedita967** [comment]
Hey, Please review once.

**Review by puneetsingh24 — COMMENTED** [review]
@Nivedita967 Not heading, Most of the text below  is still showing as it is from the link I mentioned you, Can you please rewrite all the points in your language

**There are following things needs to use during creating HTML email, If you choose to code your HTML email by hand-code:**
		

		1. If design has animation then use .gif animated file and try to avoid the use of flash and JavaScript.
		2. Your Emails should have max width of 600-700.
		3. To control the design layout and some presentation, use HTML tables .
		4. Use inline CSS to control elements within your email.
		5. CSS style declarations needs to below the body tag.
		6. Do not use CSS shorthand code.
		7. Use “display: block” for every image tag.
		8. Use six digit hexadecimal code for color “#000000”.
		9. Use spacer image for spacing between column and row to maintain the cross-browser compatibility.
		10. Use “line-height and font-size” 1pixel under “<TD>”.
		11. Use inline style for the text in each “<TD>”.
		12. Try to use Absolute images.
		13. Declare the cellpadding=”0” and cellspacing=”0” in main table tag.
		

		**What if you have to design HTML emails to be sent through Outlook?**
		

		1. Select more commands to customize your quick access toolbar(suggestion).

**Review by puneetsingh24 — APPROVED** [review]

**Review by puneetsingh24 — APPROVED** [review]

**Review by vyasriday — APPROVED** [review]

**Pull request merged**
