### PR TITLE
Added blog on Jwt vs sessions

### PR DESCRIPTION
**Pull request by uma-victor1**
#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Author Details for Blog Post Entry

id: Uma Victor
bio:I am a software developer based in Nigeria, familiar with a variety of different web technologies/frameworks and keen on always finding ways to explain things as simply as possible.
github: [my GitHub](https://github.com/uma-victor1)
linkedin: [My LinkedIn](https://www.linkedin.com/in/uma-victor-4961a9185/)
twitter: [My Twitter](https://twitter.com/umavictor_)

### CODE REVIEW

**Comment by uma-victor1** [comment]
Hi @abhir9 . 

I'm still waiting for a review.

**Comment by uma-victor1** [comment]
@pareek-narendra @puneetsingh24 @abhir9 Is there any review on this PR?

**Comment by raghunath-r-a** [comment]
> @pareek-narendra @puneetsingh24 @abhir9 Is there any review on this PR?

Hi @uma-victor1 

Sorry for the delay. We'll review this in the next 24-48 hours and let you know if any changes are necessary.

**Comment by uma-victor1** [comment]
Thank you.

**Comment by raghunath-r-a** [comment]
Hi @uma-victor1 

Overall, the article seems to be slightly off from the outline. At large, it is missing:

- Bandwidth consumption
- Attacking JWT vs. Session-based authentication

Please enrich the article and ensure that it covers everything from the outline in a clear and structured manner. 

Once you add/update the content accordingly, we'll further review in-depth and let you know any technical/content improvements necessary. 

Thank you,
@raghunath-r-a

**Comment by uma-victor1** [comment]
Hi @raghunath-r-a,

A happy new week to you!

I have updated the article with the suggestions you made.
Also added two more images and the section that was missing.

Please can you do another review on this?.

Regards,
Victor.

**Comment by raghunath-r-a** [comment]
Thank you, @uma-victor1 

We'll do both the technical and content review and let you know if any changes are necessary.

Best regards,
@raghunath-r-a

**Review by Akash-Patil — CHANGES_REQUESTED** [review]
Hi @uma-victor1 ,

Please review the suggestions and make the necessary changes.

**Comment by uma-victor1** [comment]
Hi @Akash-Patil. I have made the suggested changes.
Can you take a look?

**Review by Akash-Patil — APPROVED** [review]
The changes look good.

**Comment by raghunath-r-a** [comment]
@abhir9 @mohammed786 

Please merge this PR and publish this article. Also, please ensure:

1. The article folder name is changed to **jwt-vs-sessions**
2. The article folder is under the main folder **guest-post**

**Comment by uma-victor1** [comment]
Hi @mohammed786 @abhir9.

This PR was set to be merged a week ago.
When will it be done?

Regards,
Victor.

**Pull request merged**
