### PR TITLE
added a blog post on role based authentication with react #715

### PR DESCRIPTION
**Pull request by abhir9**
This is an article that illustrates user authentication and role assignment using LoginRadius and React.Js

#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Author Details for Blog Post Entry

id: Victory Tuduo
bio: I am a Software Developer versatile with React.Js and front-end web developer.
github: https://github.com/Victory-ET
linkedin: https://www.linkedin.com/in/tuduo-victory-7ba4641a4/

### CODE REVIEW

**Comment by raghunath-r-a** [comment]
Hi @Victory-ET 

Please give us "edit" permission for this pull request contents.

Thank you,
@raghunath-r-a

**Comment by Victory-ET** [comment]
Hi @raghunath-r-a,

I have given you edit permissions for the pull request.

Regards,
@Victory-ET

**Comment by Victory-ET** [comment]
Hi @raghunath-r-a,

It seems I did not do that properly.  Can you guide me on how to allow edit permissions for the pull request.

Regards,
@Victory-ET

**Comment by raghunath-r-a** [comment]
Hi @Victory-ET 

You could try following this: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by Victory-ET** [comment]
Hi @raghunath-r-a 

I can only see the allow edit from maintainers on pull request [715](https://github.com/LoginRadius/engineering-portal/pull/715) but I can't see the option for this current pull request 726. The option of allow edit from retainers on pull request #715 unchecks after being clicked and I am unable to provide edit permissions for this particular pull.

Regards,
@Victory-ET

**Comment by raghunath-r-a** [comment]
No problem, @Victory-ET 

We'll manage this without the edit permission.

**Comment by Victory-ET** [comment]
@raghunath-r-a 

I think I can not grant permissions because the pull request was created by @abhir9 from my own pull.

**Comment by raghunath-r-a** [comment]
@Victory-ET As a solution, please create a new pull request for this, and we'll close the current PR.

CC: @abhir9

**Comment by raghunath-r-a** [comment]
A new pull request (#732) has been created for this.

CC: @abhir9 @mohammed786

**Pull request closed without merging**
