### PR TITLE
Performing Web Authentication with LoginRadius in Vue.js

### PR DESCRIPTION
**Pull request by hannydevelop**
#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [ ] You created a branch from `dev` branch.
- [ ] You PR is raised on `dev` branch and not on`master`.
- [ ] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [ ] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [ ] Checked for any duplicate blog entry.
- [ ] Checked for all grammatical errors in the blog.
- [ ] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [ ] The content is not copy-pasted from anywhere else on the Internet.

##### Author Details for Blog Post Entry

id: Ukpai Ugochi
bio: Ukpai Ugochi is a female Nigerian with a Bachelor's degree in Marine Engineering and bootcamp certificates in software development. She's a fullstack JavaScript developer on the MEVN stack who loves to share knowledge about her transition from marine engineering to software development in the form of writing, to encourage people who love software development and don't know where to begin.
github: https://github.com/hannydevelop/
linkedin: https://www.linkedin.com/in/ugochi-ukpai-1361b0198
twitter: https://twitter.com/hannydevelop/

### CODE REVIEW

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
@hannydevelop Wherever you mention LoginRadius it should be together, not like "login radius" and both L and R should be capital "LoginRadius". Please do the necessary changes in the blog

**Comment by hannydevelop** [comment]
Hello @puneetsingh24 I have implemented all of the changes you requested for. Please let me know if you have any questions or suggestions.

**Comment by pareek-narendra** [comment]
@hannydevelop 
Thank you for your contribution and for sharing valuable information.
I've made a few minor changes in this please go through it and apart from this, I have a few suggestions for you.

 - Cover Image should be in png/jpg format, update the relative image. We do support GIF only in the page content.
 - Folder name should be separated with "-" and a small casing without space.
 - "Ignore the "Try Signing Up Now" button. This is because we'll get an error since we've not set up our Vue.js application yet.": This should work and please share if you are facing any issue with this.
 - Info in heading User Account is not appropriate (Should not recommend management APIs for front-end registration): Please use [Authentication APIs](https://www.loginradius.com/docs/developer/references/api/authentication#auth-user-registration-by-email) for front-end registrations otherwise it reveals your secret key on the frontend.
 - Please add a GIF or images on the page where you can display your implemented demo's flow of Login/Registration.
 - Add author info in content/author.yaml 

Thanks in advance and looking forward to more such contributions in the future as well.

**Review by pareek-narendra — CHANGES_REQUESTED** [review]
Changes requested

**Comment by pareek-narendra** [comment]
@hannydevelop are you working on the changes?

**Comment by raghunath-r-a** [comment]
The PR is being closed as there has been no response from the author.

**Pull request closed without merging**
