### PR TITLE
title: created blog on COMPLETE GIT (VERSION CONTROL SYSTEM)

### PR DESCRIPTION
**Pull request by SaravananVijayamuthu**
#### Checklist

- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] Checked for all grammatical errors in the blog.
- [x] Checked for any duplicate blog entry.

### CODE REVIEW

**Comment by vyasriday** [comment]
Hey @SaravananVijayamuthu, Thanks for Contributing to LoginRadius Engineering Blog. We will review it and let you know of any changes necessary. Meanwhile, please fill this [form](https://forms.gle/aUYJXoVJVivPgGuM8) to become eligible to get swags from LoginRadius for your contribution.

**Comment by vyasriday** [comment]
Hey @SaravananVijayamuthu I see a lot of file changes due to image optimization using coming from imgbot. Can you please revert all those changes?

**Comment by SaravananVijayamuthu** [comment]
> Hey @SaravananVijayamuthu I see a lot of file changes due to image optimization using coming from imgbot. Can you please revert all those changes?

I have done it please do check now!!

**Comment by vyasriday** [comment]
There is one more thing. Did you rebase with our `dev` branch.  We accept PR on dev branch before they go into `master` from all contributors. If not,  Can you please rebase your branch from `dev` and submit a Pull request on  `dev` branch ?

**Comment by SaravananVijayamuthu** [comment]
> There is one more thing. Did you rebase with our `dev` branch. We accept PR on dev branch before they go into `master` from all contributors. If not, Can you please rebase your branch from `dev` and submit a Pull request on `dev` branch ?

Yes, I have rebased now to `dev` and created a new pr.

**Comment by vyasriday** [comment]
Thanks @SaravananVijayamuthu . I will close this PR now. and

**Pull request closed without merging**
