### PR TITLE
Flutter blog

### PR DESCRIPTION
**Pull request by Hard-Coder05**
#### Checklist

- [x ] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] You created a branch from `dev` branch
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] Checked for all grammatical errors in the blog.
- [x] Checked for any duplicate blog entry.
- [x] You PR is raised on `dev` branch and not on`master`.

##### Description of change
Raised this PR on issue #233 

##### Author Details for Blog Post Entry

id: Siddharth Mishra
bio: I am a budding flutter developer.
github: https://github.com/Hard-Coder05
linkedin: https://www.linkedin.com/in/smishra1605/
twitter: https://twitter.com/im_siddhart

### CODE REVIEW

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
Hello Siddharth,

We found out that most of the content on the blog is copy-pasted from another site.  As part of our code of conduct, we encourage you to create your own content in your own language. We are strongly against plagiarism and hence do not accept blog that are copy pasted from Internet.

Please update the content of the text in your own language and please try to add some more information in the blog as currently, it contains very less information to consider it as a good blog

**Comment by Hard-Coder05** [comment]
@puneetsingh24  I just took ideas from the net and compiled it. I have made changes, You can review it again !

**Review by puneetsingh24 — CHANGES_REQUESTED** [review]
Hello @Hard-Coder05 

Thanks for writing this blog and we appreciate your effort while writing this. However, as per our project contribution guidelines, we need the blog of a minimum of 600 words.

Please make sure your post is lengthy enough.

**Comment by Hard-Coder05** [comment]
@puneetsingh24 Okay Surely I will add!

**Pull request closed without merging**
