### PR TITLE
Blogpost on Best Hacking Tools

### PR DESCRIPTION
**Pull request by Akshay-Nagle**
#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Description of change

Blogpost on Best Hacking Tools

##### Author Details for Blog Post Entry

id: Akshay Nagle
bio: Seeking opportunity in Ethical Hacking
github: https://github.com/Akshay-Nagle
linkedin: https://www.linkedin.com/in/akshay-nagle-3408a1179/
twitter: https://twitter.com/akshaynagle

This PR is related with #233

### CODE REVIEW

**Comment by Akshay-Nagle** [comment]
@puneetsingh24 Please kindly review this PR and suggest the changes required (if any)

**Comment by Akshay-Nagle** [comment]
@vyasriday @puneetsingh24 Please review this PR

**Comment by vyasriday** [comment]
@Akshay-Nagle Please remove any `_` from your folder name. We only support `-`.  `/Best_hacking_tools` should be `/best-hacking-tools`.

**Comment by Akshay-Nagle** [comment]
@vyasriday I have changed the folder name as you asked. Please let me know if there is any other modifications required.

**Review by vyasriday — APPROVED** [review]

**Review by puneetsingh24 — APPROVED** [review]

**Pull request merged**
