### PR TITLE
added a blog post on role based authentication with react

### PR DESCRIPTION
**Pull request by Victory-ET**
This is an article that illustrates user authentication and role assignment using LoginRadius and React.Js

#### Please note that in case of below checklist not updated accordingly, the maintainers have the right to immediately close your pull request.

- [x] You created a branch from `dev` branch.
- [x] You PR is raised on `dev` branch and not on`master`.
- [x] Blog follows [Blog Guidelines](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md).
- [x] You have read the [Contribution Guidlines](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md) before creating this PR.
- [x] Checked for any duplicate blog entry.
- [x] Checked for all grammatical errors in the blog.
- [x] You have not published the blog content anywhere else on the internet on platforms like medium, dev.to etc.
- [x] The content is not copy-pasted from anywhere else on the Internet.

##### Author Details for Blog Post Entry

id: Victory Tuduo
bio: I am a Software Developer versatile with React.Js and front-end web developer.
github: https://github.com/Victory-ET
linkedin: https://www.linkedin.com/in/tuduo-victory-7ba4641a4/

### CODE REVIEW

**Comment by Victory-ET** [comment]
@abhir9 @pareek-narendra @puneetsingh24 . Please when will the review process take place?

**Comment by raghunath-r-a** [comment]
Hi @Victory-ET 

We'll review this in the next 72 hours and get back to you if any changes are necessary.

**Comment by raghunath-r-a** [comment]
Hi @Victory-ET 

I have reviewed the article, and it seems to be missing "Handling User Authentication" and related content, as per the finalized outline. While you may have covered this in "Using the LoginRadius API," it is important to cover "Handling User Authentication," and it's relevant subtopics to ensure readers can be clear and get value from the content.

Apart from this, please try editing the article for consistency and conciseness. For example, ensure that where applicable:

- Please ensure "LoginRadius" is written consistently with uppercase L and R. Similarly, "ReactJS" with an uppercase S.
- Please edit to remove where sentences are needlessly wordy and ensure grammar is solid, among others.

All of these changes can make the article better and provide more value to readers. Would you mind making these changes and letting us know? 

After receiving these changes, we'll do an in-depth technical/content review to move forward.

Please feel free to ask any questions you may have.

Thank you,
@raghunath-r-a

**Comment by Victory-ET** [comment]
Hi @raghunath-r-a,

I have made the requested changes and added a new section for handling user authentication. 

Regards,

@Victory-ET

**Review by abhir9 — APPROVED** [review]

**Comment by abhir9** [comment]
older PR get merged without content review. This has been reverted , @raghunath-r-a   please refer new PR

https://github.com/LoginRadius/engineering-portal/pull/726

**Pull request merged**
